config/routes.rb
AddressRef::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations" } do
    get "/login", :to => "devise/sessions#new"
    get "/logout", :to => "devise/sessions#destroy"
    get "/register", :to => "devise/registrations#new"
  end

  resources :contact_lines

  resources :contacts, :collection => { :search => :post } do
    member do
     get 'search'
    end
    resources :contact_lines
  end

  resources :invoice_items

  resources :invoices

  resources :orders

  root :to => 'homes#index'

end

app/models/contact_line.rb
class ContactLine < ActiveRecord::Base
  belongs_to :contact
  # validates_presence_of :value
  
  def show_label
    label.gsub(/(phone|email|address|chat|website)_/,'').titleize
  end
  
end

app/controllers/contact_lines_controller.rb
class ContactLinesController < ApplicationController

  # POST /contact_lines
  # POST /contact_lines.xml
  def create
    @contact_line = ContactLine.new(params[:contact_line])
    
    respond_to do |format|
      if @contact_line.save
        flash.now[:notice] = "#{params[:section]} was successfully added."
        format.html { render :partial => "edit", :locals => {:cl => @contact_line, :section => params[:section] } }
        format.xml  { render :xml => @contact_line, :status => :created, :location => @contact_line }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @contact_line.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /contact_lines/1
  # DELETE /contact_lines/1.xml
  def destroy
    @contact_line = ContactLine.find(params[:id])
    flash[:notice] = "#{@contact_line.show_label} removed"
    @contact_line.destroy
    respond_to do |format|
      format.html { render :layout => false }
      format.xml  { head :ok }
    end
  end
end

app/helpers/contact_lines_helper.rb
module ContactLinesHelper
end

app/views/contact_lines/_edit.html.erb
<% fields_for :contact_line, cl do |fcl| %>
<tr id="contact_line_<%= cl.id %>">
    <th>
        <%= select_tag "contact_line[#{cl.id}][label]", options_for_select(Contact.labels(section.downcase), [cl.id, cl.label]) %>
    </th>
    <td>
        <%= fcl.text_field :value, :index => cl.id, :default => section, :size => 25 %>
        <%= link_to 'remove', contact_line_path(cl), :onclick => "remove_contact_line(this,'#{form_authenticity_token}'); return false"  %>
    </td>
</tr>
<% end %>

<%= render :partial => 'shared/flash', :locals => {:flash => flash} %>

app/views/contact_lines/destroy.html.erb
<script type="text/javascript" charset="utf-8">
    $('#contact_line_<%= @contact_line.id %>').remove();
</script>

<%= render :partial => 'shared/flash', :locals => {:flash => flash} %>