config/routes.rb
AddressRef::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations" } do
    get "/login", :to => "devise/sessions#new"
    get "/logout", :to => "devise/sessions#destroy"
    get "/register", :to => "devise/registrations#new"
  end

  resources :contact_lines

  resources :contacts, :collection => { :search => :post } do
    member do
     get 'search'
    end
    resources :contact_lines
  end

  resources :invoice_items

  resources :invoices

  resources :orders

  root :to => 'homes#index'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  has_many :contact_lines, :dependent => :destroy
  
  @@labels = %w( phone_main phone_work phone_home phone_mobile phone_fax phone_evening phone_factory phone_other ) +
             %w( email_main email_work email_personal ) +
             %w( website_main website_work website_personal ) +
             %w( chat_aim chat_jabber chat_msn chat_gtalk chat_skype chat_yahoo ) +
             %w( address_street address_state address_city address_postal_code address_country )
             
  
  def main_name
    is_company? ? company_name : name
  end
  
  def second_name
    is_company? ? name : company_name
  end
  
  def name
    "#{first_name || 'No'} #{last_name || 'Name'}"
  end
  
  def self.search(query)
    self.find(:all, :conditions => ["first_name LIKE ? OR last_name LIKE ? OR company_name LIKE ? OR notes LIKE ?", "%#{query}%", "%#{query}%", "%#{query}%", "%#{query}%"])
  end
  
  def update_all(params)
    transaction do
      update_attributes(params[:contact])
      
      params[:contact_line].each do |cl|
        logger.debug "#{cl.inspect}"
        if cl[0].to_i == 0
          contact_lines.find_or_create_by_label(cl[0]).update_attribute('value',cl[1][:value])
        else
          contact_line = contact_lines.find(cl[0])
          cl[1][:value].blank? ? contact_line.destroy : contact_line.update_attributes(cl[1]) 
        end
      end
      
      if main_name.blank? && second_name.blank?
        destroy
        return false
      else
        if company_name.blank? && is_company?
          update_attribute('is_company', false)
        elsif name.blank? && !is_company?
          update_attribute('is_company', true)
        end
        return true
      end
    end
  end
  
  @@labels.each do |label|
    define_method(label) do
      cl = read_contact_line(label)
      cl.value if cl
    end
    define_method("#{label}=") do |value|
      write_contact_line(label, value)
    end
  end
  
  def self.labels(prefix)
    @@labels.select { |label| label.include?(prefix) }.map { |label| [label.gsub("#{prefix}_", '').titleize, label] }
  end
  
  def phones
    contact_lines.find(:all, :conditions => "label LIKE 'phone%'")
  end
  
  def chats
    contact_lines.find(:all, :conditions => "label LIKE 'chat%'")
  end
  
  def websites
    contact_lines.find(:all, :conditions => "label LIKE 'web%'")
  end
  
  def emails
    contact_lines.find(:all, :conditions => "label LIKE 'email%'")
  end
  
  def address_lines
    contact_lines.find(:all, :conditions => "label LIKE 'address%'")
  end
  
  def map_address
    "#{address_line_value(:address_street)} #{address_line_value(:address_city)} #{address_line_value(:address_state)} #{address_line_value(:address_postal_code)} #{address_line_value(:address_country)}"
  end
  
  def address_line(address_line)
    cl = contact_lines.find_by_label(address_line.to_s)
    (cl && cl.value.blank?) ? ContactLine.new(:label => address_line.to_s) : cl
  end
  
  def address_line_value(address_line)
    (cl = address_line(address_line)) ? cl.value : nil
  end
  
  private
  def read_contact_line(label)
    contact_lines.find_by_label(label)
  end
  
  def write_contact_line(label, value)
    cl = contact_lines.find_or_create_by_label(label)
    cl.value = value
    cl.save
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  # GET /contacts
  # GET /contacts.xml
  def index
    @contacts = Contact.all(:order => "company_name, first_name")
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @contacts.to_xml(:dasherize => false, :methods => [:main_name], :only => [:name, :id] ) }
    end
  end
  
  # GET /contacts/1
  # GET /contacts/1.xml
  def show
    @contact = Contact.find(params[:id])

    respond_to do |format|
      format.html { render :layout => false }
      format.xml
    end
  end
  
  # GET /search/q?
  # GET /search.xml/q?
  # TODO: set routes
  def search
    @contacts = Contact.search(params[:q])
    
    respond_to do |format|
      format.html { render :action => "index" }
      format.xml  { render :xml => @contacts.to_xml(:dasherize => false, :methods => [:main_name], :only => [:name, :id] ) }
    end
  end

  # GET /contacts/new
  # GET /contacts/new.xml
  def new
    @contact = Contact.create
    %w{phone_main phone_fax email_main}.each do |label|
      ContactLine.create({:label => label, :contact => @contact})
    end
    render :action => "edit", :layout => false
  end

  # GET /contacts/1/edit
  def edit
    @contact = Contact.find(params[:id])
    render :layout => false
  end

  # POST /contacts
  # POST /contacts.xml
  def create
    @contact = Contact.new(params[:contact])

    respond_to do |format|
      if @contact.save && @contact.update_all(params)
        flash.now[:notice] = 'Contact was successfully created.'
        format.html { render :action => "show", :layout => false }
        format.xml  { render :xml => @contact, :status => :created, :location => @contact }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @contact.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /contacts/1
  # PUT /contacts/1.xml
  def update
    @contact = Contact.find(params[:id])
    respond_to do |format|
      if @contact.update_all(params)
        flash.now[:notice] = 'Contact was successfully updated.'
        format.html { render :action => "show", :layout => false }
        format.xml  { head :ok }
      else
        format.html { render :action => "failed_update", :layout => false }
        format.xml  { render :xml => @contact.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.xml
  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy

    respond_to do |format|
      format.html { render :layout => false }
      format.xml  { head :ok }
    end
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/destroy.html.erb
<script type="text/javascript" charset="utf-8">
    $('#contact_list ul li.selected').remove();
	$('#contact_list ul li:first').click().focus();
</script>

app/views/contacts/edit.html.erb
<% form_for @contact do |f| %>
    <h2>
        <div class="photo">
            <img src="/images/person.gif" alt="" align="top" />
        </div>
        <div class="contact_name">
            <%= f.text_field :first_name, :size => 15, :default => "First" %><%= f.text_field :last_name, :size => 15, :default => "Last" %><br />
            <%= f.text_field :company_name, :size => 30, :default => "Company" %><br />
            <%= f.check_box :is_company %> Company?
        </div>
    </h2>
    <table border="0" cellspacing="0" cellpadding="0">
    <% %w{ Phone Email Website Chat }.each do |section| %>
        <tr id="<%= section %>">
            <th><%= section.pluralize %></th>
            <td><%= link_to "add", contact_lines_path(:contact_line => {:contact_id => @contact, :label => Contact.labels(section.downcase).first[1]}, :section => section), :class => "add-cl-row"  %></td>
        </tr>
        <% @contact.send(section.pluralize.downcase).each do |cl| %>
            <%= render :partial => 'contact_lines/edit', :locals => {:cl => cl, :section => section} %>
        <% end %>
    <% end %>
        <tr>
            <th>Address</th>
            <td>
                <% fields_for :contact_line, (cl = @contact.address_line(:address_street)) do |fcl| %>
                    <%= fcl.text_field :value, :index => 'address_street',  :size => 24, :default => "Street" %>
                <% end %>
                <br />
                <% fields_for :contact_line, (cl = @contact.address_line(:address_city)) do |fcl| %>
                    <%= fcl.text_field :value, :index => 'address_city', :size => 12, :default => "City" %>
                <% end %>
                <% fields_for :contact_line, (cl = @contact.address_line(:address_state)) do |fcl| %>
                    <%= fcl.text_field :value, :index => 'address_state', :size => 9, :default => "State" %>
                <% end %>
                <% fields_for :contact_line, (cl = @contact.address_line(:address_postal_code)) do |fcl| %>
                    <%= fcl.text_field :value, :index => 'address_postal_code', :size => 6, :default => "Zip" %>
                <% end %>
                <br />
                <% fields_for :contact_line, (cl = @contact.address_line(:address_country)) do |fcl| %>
                    <%= fcl.text_field :value, :index => 'address_country', :size => 18, :default => "Country" %>
                <% end %>
            </td>
        </tr>
        <tr>
          <th>Notes:</th>
          <td>
            <%= f.text_area :notes, :size => "33x3" %>
          </td>
        </tr>
    </table>
<% end %>


<script type="text/javascript" charset="utf-8">
    check_list_name('<%= @contact.id %>');
    $('form.edit_contact input').each(function(){
       show_default_value(this); 
    }).focus(function(){
       hide_default_value(this); 
    }).blur(function(){
       show_default_value(this); 
    });
    $('#edit-link').html('<%=escape_javascript link_to image_tag("save.png", :size => "52x22"), contact_path(@contact) %>');
    $('#edit-link a').click(function(){
        save_contact(this.href); 
        return false;
    });
    $('form.edit_contact').submit(function(){
        save_contact(this.action); 
        return false;
    });
    $("a.add-cl-row").click(function() {
        elem = this;
        jQuery.post(elem.href,{_method: "post", authenticity_token: "<%= form_authenticity_token %>"}, function(data){
    		$(elem).parent().parent().after(data); 
    	});
        return false;
    });
</script>

<%= render :partial => 'shared/flash', :locals => {:flash => flash} %>

app/views/contacts/failed_update.html.erb
<script type="text/javascript" charset="utf-8">
    $('#contact_<%= @contact.id %>_name').remove();
    $('#contact_list ul li:first').click().focus();
</script>

app/views/contacts/index.html.erb
<div id="container">
    <div id="contact_list">
        <h2>Names <span>
          <small>Total: <%= @contacts.size  %></small>
        </span></h2>

        <ul>
            <% for contact in @contacts %>
              <li id="contact_<%= contact.id %>_name" path="<%= contact_path contact %>">
                <%=h contact.main_name %>
              </li>
            <% end %>
        </ul>
    </div>

    <div id="contact_detail">
        <div class="editarea">
            <h2>
                <div class="photo">
                    <img src="/images/person.gif" align="top" />
                </div>
                <div class="contact_name">
                    Loading...
                </div>
            </h2>
            <table border="0" cellspacing="0" cellpadding="0">
                <tbody>
                    <tr>
                        <th>Loading...</th>
                        <td>&nbsp;</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <%= link_to image_tag('add.png', :size => '29x22'), new_contact_path, :id => "new-link"  %>
    <span id="delete-link">
        
    </span>
    <span id="edit-link">
        
    </span>
    <br class="clearfloat" />
</div>

app/views/contacts/new.html.erb
<h1>New contact</h1>

<%= error_messages_for :contact %>

<% form_for(@contact) do |f| %>
  <p>
    <b>Name</b><br />
    <%= f.text_field :name %>
  </p>

  <p>
    <b>Company name</b><br />
    <%= f.text_field :company_name %>
  </p>

  <p>
    <b>Is company</b><br />
    <%= f.check_box :is_company %>
  </p>

  <p>
    <b>Updated by</b><br />
    <%= f.text_field :updated_by %>
  </p>

  <p>
    <%= f.submit "Create" %>
  </p>
<% end %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<h2>
    <div class="photo">
        <img src="/images/person.gif" alt="" align="top" />
    </div>
    <div class="contact_name">
        <%=h @contact.main_name %><br />
        <small><%=h @contact.second_name %></small>
    </div>
</h2>
    <table border="0" cellspacing="0" cellpadding="0">
        <% %w{phones emails websites chats}.each do |cat| %>
            <% for cl in @contact.send(cat) %>
            <tr>
                <th><%= cl.show_label %></th>
                <% if cl.label.include?('email') %>
                    <td><a class="email-link" href="mailto:<%=h @contact.main_name %><<%=h cl.value %>>"><%=h cl.value %></a></td>
                <% elsif cl.label.include?('website') %>
                    <td><a class="email-link" href="<%=h cl.value %>"><%=h cl.value %></a></td>
                <% else %>
                    <td><%=h cl.value %></td>
                <% end %>
            </tr>
            <% end %>
        <% end %>
            <tr>
                <th>&nbsp;</th>
            </tr>
            <tr>
                <th>Address</th>
                <td>
                    <a class="map-link" target="_blank" href="http://maps.google.com/maps?q=<%= @contact.map_address %>">
                        <%= (cl = @contact.address_line(:address_street)) ? cl.value : nil %><br />
                        <%= (cl = @contact.address_line(:address_city)) ? cl.value : nil %>
                        <%= (cl = @contact.address_line(:address_state)) ? cl.value : nil %>
                        <%= (cl = @contact.address_line(:address_postal_code)) ? cl.value : nil %><br />
                        <%= (cl = @contact.address_line(:address_country)) ? cl.value : nil %>
                    </a>
                </td>
            </tr>
            <tr>
                <th>Notes</th>
                <td>
                  <%= @contact.notes %>
                </td>
            </tr>
    </table>
    
<script type="text/javascript" charset="utf-8">
    stoken = '<%= form_authenticity_token %>'
    $('#delete-link').html('<%=escape_javascript link_to image_tag("delete.png", :size => "29x22"), contact_path(@contact), :onclick => "remove_contact_line(this,stoken); return false" %>');
    $('#edit-link').html('<%=escape_javascript link_to image_tag("edit.png", :size => "52x22"), edit_contact_path(@contact) %>');
    $('#edit-link a').click(function() {
        $('#contact_detail .editarea').load(this.href);
    	return false;
    });
    $('#contact_list ul li').removeClass("selected");
    $('#contact_<%= @contact.id %>_name').html('<%= @contact.main_name %>').addClass('selected');
</script>

<%= render :partial => 'shared/flash', :locals => {:flash => flash} %>