config/routes.rb
AddressRef::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations" } do
    get "/login", :to => "devise/sessions#new"
    get "/logout", :to => "devise/sessions#destroy"
    get "/register", :to => "devise/registrations#new"
  end

  resources :contact_lines

  resources :contacts, :collection => { :search => :post } do
    member do
     get 'search'
    end
    resources :contact_lines
  end

  resources :invoice_items

  resources :invoices

  resources :orders

  root :to => 'homes#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
       "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <title>ContactLines: <%= controller.action_name %></title>
  <%= stylesheet_link_tag 'scaffold' %>
  <%= stylesheet_link_tag 'common' %>
  <%= javascript_include_tag 'jquery-1.2.1.js' %>
  <%= javascript_include_tag 'jquery.corner.js' %>
  <%= javascript_include_tag 'application' %>
</head>
<body  class="twocolumn">
<% if current_user %>
    <div id="header">
        <h1>Address Book</h1>
        <%  form_tag(contacts_path, :id => "search") do %>
            <div id="flash">

            </div>
            <table border="0" cellspacing="0" cellpadding="0">
                <tr>
                    <td><input type="text" name="q" id="q" value="<%= params[:q] %>" default="Search..." /></td>
                    <td><input type="image" src="/images/search.png" /><%= (link_to image_tag('close.png'), contacts_path) if params[:q] %></td>
                </tr>
            </table>
        <% end %>
        <br class="clearfloat" />
    </div>
<%end%>
<%= yield  %>
</body>
</html>

app/views/layouts/contact_lines.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
       "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <title>ContactLines: <%= controller.action_name %></title>
  <%= stylesheet_link_tag 'scaffold' %>
</head>
<body>

<p style="color: green"><%= flash[:notice] %></p>

<%= yield  %>

</body>
</html>

app/views/layouts/contacts.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
       "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <title>Contacts: <%= controller.action_name %></title>
  <%= stylesheet_link_tag 'common' %>
</head>
<body  class="twocolumn">
    
    <div id="header">
        <h1>Address Book</h1>
        <%#form_tag(search_contacts_path, :id => "search") do %>
            <div id="flash">
                
            </div>
            <table border="0" cellspacing="0" cellpadding="0">
                <tr>
                    <td><input type="text" name="q" id="q" value="<%= params[:q] %>" default="Search..." /></td>
                    <td><input type="image" src="/images/search.png" /><%= (link_to image_tag('close.png'), contacts_path) if params[:q] %></td>
                </tr>
            </table>
        <%# end %>
        <br class="clearfloat" />
    </div>

<%= yield  %>

<%= javascript_include_tag 'jquery-1.2.1.js' %>
<%= javascript_include_tag 'jquery.corner.js' %>
<%= javascript_include_tag 'application' %>
</body>
</html>